server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        ### User Service Route Settings ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/profile-image/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/profile-image/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/docs/index.html
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        ### Meeting Service Route Settings ###
        - id: meeting-service
          uri: lb://MEETING-SERVICE
          predicates:
            - Path=/meetings/**
          filters:
            - RemoveRequestHeader=Cookie
            - JwtAuthentication=ROLE_USER

        - id: meeting-service
          uri: lb://MEETING-SERVICE
          predicates:
            - Path=/meeting-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/meeting-service/(?<segment>.*), /$\{segment}
            - JwtAuthentication=ROLE_USER

        - id: meeting-service
          uri: lb://MEETING-SERVICE
          predicates:
            - Path=/meeting-service/docs/index.html
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/meeting-service/(?<segment>.*), /$\{segment}

        ### Course Service Route Settings ###
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/courses/**

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/course-service/(?<segment>.*), /$\{segment}

        - id: course-service
          uri: lb://COURCE-SERVICE
          predicates:
            - Path=/course-service/docs/index.html
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/course-service/(?<segment>.*), /$\{segment}

        ### Auth Service Route Settings ###
        ## login
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/authorize/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/actuator/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/docs/index.html
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}


