spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        ### User Service Route Settings ###
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/profile-image/**

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}

        ### Meeting Service Route Settings ###
        - id: meeting-service
          uri: lb://MEETING-SERVICE
          predicates:
            - Path=/meetings/**
          filters:
            - RemoveRequestHeader=Cookie
            - JwtAuthentication=ROLE_USER

        - id: meeting-service
          uri: lb://MEETING-SERVICE
          predicates:
            - Path=/meeting-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/meeting-service/(?<segment>.*), /$\{segment}

        ### Course Service Route Settings ###
        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/courses/**

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/course-service/(?<segment>.*), /$\{segment}

        ### Auth Service Route Settings ###
        ## login
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/oauth2/authorize/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}

###############
        # for test
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-test-api/**